### PR TITLE
Remove workaround code, see if Zip 'Name' header obviates it

### PR DESCRIPTION
**Pull request by teodesian**
Test this out with a real Selenium head and see how it works out.

### CODE REVIEW

**Comment by jamadam** [comment]
@teodesian 
How do you think second argument of upload file?
hand-made zip binary still possibly contain directories and the workarround is needed for the case. 
Is it acceptable to remove the API from POD?

**Comment by teodesian** [comment]
1. Not sure I follow, but if you're referring to going with the upload_file_improve2 branch rather than this one, I have no problem with that.  If IO::Compress::Zip is the only thing providing a string we can use, then so be it.
2. I think the warning I put in about passing raw data is (mostly) adequate:

"When passing raw data, be advised that it expects a zipped
   and then base64 encoded version of a single file.
   Multiple files are not supported by the remote server."

I would say changing that to be "Multiple files and/or directories are not supported..." should be adequate warning not to engage in the dangerous use case.

I'll shoot another commit down to that effect.

**Comment by teodesian** [comment]
Oh, and if we decide to go with upload_file_improve2 over this branch, be sure to cherry-pick the warning commit above into that branch (it still applies).

**Comment by jamadam** [comment]
Thanks for the PR.
I may not follow you about cherry-picking so please review my commit later.

**Pull request merged**
